//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : BombedWall.h
//  @ Date : 6/14/2012
//  @ Author : 
//
//


#if !defined(_BOMBEDWALL_H)
#define _BOMBEDWALL_H

#include "Wall.h"

class BombedWall : public Wall {
public:
	BombedWall();
	~BombedWall();
};

BombedWall::BombedWall() {

}

BombedWall::~BombedWall() {

}
#endif  //_BOMBEDWALL_H
