//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : EnchantedWall.h
//  @ Date : 6/14/2012
//  @ Author : 
//
//


#if !defined(_ENCHANTEDWALL_H)
#define _ENCHANTEDWALL_H

#include "Wall.h"

class EnchantedWall : public Wall {
    public:
    EnchantedWall();
	~EnchantedWall();
};

EnchantedWall::EnchantedWall() {
    cout << "Entra al constructor de paredes encantadas" << endl;
}

EnchantedWall::~EnchantedWall() {
}
#endif  //_ENCHANTEDWALL_H
