//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : EnchantedDoor.h
//  @ Date : 6/14/2012
//  @ Author : 
//
//


#if !defined(_ENCHANTEDDOOR_H)
#define _ENCHANTEDDOOR_H

#include "Door.h"

class EnchantedDoor : public Door {
public:
	EnchantedDoor();
	~EnchantedDoor();
};

EnchantedDoor::EnchantedDoor() {
	cout << "Entra al constructor de puertas encantadas" << endl;
}

EnchantedDoor::~EnchantedDoor() {
}

#endif  //_ENCHANTEDDOOR_H
