//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : EnchantedMazeFactory.h
//  @ Date : 6/14/2012
//  @ Author : 
//
//



#if !defined(_ENCHANTEDMAZEFACTORY_H)
#define _ENCHANTEDMAZEFACTORY_H

#include "Maze.h"
#include "MazeFactory.h"
#include "EnchantedDoor.h"
#include "EnchantedRoom.h"
#include "EnchantedWall.h"

class EnchantedMazeFactory : public MazeFactory {
public:
	Maze* createMaze();
	Wall* createWall();
	Door* createDoor();
	Room* createRoom();
};

Maze* EnchantedMazeFactory::createMaze() {
	return new Maze();
}

Wall* EnchantedMazeFactory::createWall() {
	return new EnchantedWall();
}

Door* EnchantedMazeFactory::createDoor() {
	return new EnchantedDoor();
}

Room* EnchantedMazeFactory::createRoom() {
	return new EnchantedRoom();
}

#endif  //_ENCHANTEDMAZEFACTORY_H
