//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : EnchantedRoom.h
//  @ Date : 6/14/2012
//  @ Author : 
//
//


#if !defined(_ENCHANTEDROOM_H)
#define _ENCHANTEDROOM_H

#include "Room.h"

class EnchantedRoom : public Room {
    public:
    EnchantedRoom();
    ~EnchantedRoom();
};

EnchantedRoom::EnchantedRoom() {
    cout << "Entra al constructor de cuartos encantados" << endl;
}

EnchantedRoom::~EnchantedRoom() {
    cout << "Entra al destructor de cuartos encantados" << endl;
}

#endif  //_ENCHANTEDROOM_H
