//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Modelo
//  @ File Name : EnchantedDoor.cpp
//  @ Date : 6/14/2012
//  @ Author : 
//
//


#include "EnchantedDoor.h"

void EnchantedDoor::Door() {
    cout << "Entra al constructor de puertas encantadas" << endl;
}

